### ISSUE TITLE
Bug with monadic joins

### ISSUE THREAD

**Issue by ErunamoJAZZ** [slick/slick#1316] opened 2015-10-13 20:54 UTC
Hello!

I had problems with new slick, because this show me the exception `slick.SlickTreeException: Unreachable reference to s2 after resolving monadic joins` 

So... i made a little example for explain this: 3 tables, A, B and C, and a table ABC with foreign keys to A, B and C.

```scala
object testWithJoins {

  //TABLE A
  case class a(id:Option[Int],name:String)
  class A_Table(_tableTag: Tag) extends Table[a](_tableTag, "A") {
    def * = (id.?, name) <>(a.tupled, a.unapply)
    val id: Rep[Int] = column[Int]("ID", O.AutoInc, O.PrimaryKey)
    val name: Rep[String] = column[String]("NAME", O.Length(254, varying = true))
  }
  val a_query = new TableQuery(tag => new A_Table(tag))

  //TABLE B
  case class b(id:Option[Int],name:String)
  class B_Table(_tableTag: Tag) extends Table[b](_tableTag, "B") {
    def * = (id.?, name) <>(b.tupled, b.unapply)
    val id: Rep[Int] = column[Int]("ID", O.AutoInc, O.PrimaryKey)
    val name: Rep[String] = column[String]("NAME", O.Length(254, varying = true))
  }
  val b_query = new TableQuery(tag => new B_Table(tag))

  //TABLE C
  case class c(id:Option[Int],name:String)
  class C_Table(_tableTag: Tag) extends Table[c](_tableTag, "C") {
    def * = (id.?, name) <>(c.tupled, c.unapply)
    val id: Rep[Int] = column[Int]("ID", O.AutoInc, O.PrimaryKey)
    val name: Rep[String] = column[String]("NAME", O.Length(254, varying = true))
  }
  val c_query = new TableQuery(tag => new C_Table(tag))


  //TABLE ABC
  case class abc(id:Option[Int],id_a:Int,id_b:Int,id_c:Int)
  class ABC_Table(_tableTag: Tag) extends Table[abc](_tableTag, "ABC") {
    def * = (id.?, id_a, id_b, id_c) <> (abc.tupled, abc.unapply)

    val id: Rep[Int] = column[Int]("ID", O.AutoInc, O.PrimaryKey)
    val id_a: Rep[Int] = column[Int]("ID_A")
    val id_b: Rep[Int] = column[Int]("ID_B")
    val id_c: Rep[Int] = column[Int]("ID_C")

    lazy val a_Fk = foreignKey("a_fk", id_a, a_query)(r => r.id, onUpdate = ForeignKeyAction.Cascade, onDelete = ForeignKeyAction.NoAction)
    lazy val b_Fk = foreignKey("b_fk", id_b, b_query)(r => r.id, onUpdate = ForeignKeyAction.Cascade, onDelete = ForeignKeyAction.NoAction)
    lazy val c_Fk = foreignKey("c_fk", id_c, c_query)(r => r.id, onUpdate = ForeignKeyAction.Cascade, onDelete = ForeignKeyAction.NoAction)
  }
  val abc_query = new TableQuery(tag => new ABC_Table(tag))


  /*
  test 1 fails with Slick 3.1.0
   */
  def test1 = {
    val q1 = for {
      a <- a_query
      b <- b_query
      c <- c_query
      abc <- abc_query
      if a.id === abc.id_a &&
        b.id === abc.id_b &&
        c.id === abc.id_c &&
        b.name.like("test")
    } yield (a.id, c.id)

    println("Test 1:")
    println(q1.result.statements.head)
  }
  
  /*
  but, if we change it a bit... then works.
   */
  def test2 = {
    val q1 = for {
      a <- a_query
      c <- c_query
      (b, abc) <- b_query join abc_query on (_.id === _.id_b)
      if a.id === abc.id_a &&
        c.id === abc.id_c &&
        b.name.like("test")
    } yield (a.id, c.id)

    println("Test 2:")
    println(q1.result.statements.head)
  }
}
```

I hope this will help to people who had problems trying to migrate to new slick.

**Comment by timgautier** [comment] 2015-10-15 20:07
Yes, we're seeing this bug also. Refactoring the query from using a `for` comprehension to using `join` seems to work around it, indicating it's an issue with the `for` comprehension code.

**Comment by ErunamoJAZZ** [comment] 2015-10-15 20:11
Yeah, i don't could migrate my app to the new slick, because we use a lot of `for { }` queries, I really dont know if this is for design, or if it was a bug.

We are using slick 3.0 for now.

**Comment by timgautier** [comment] 2015-10-15 20:32
Ah, when I said it's an issue with the `for` comprehension code, I meant the slick code that translates a `for` comprehension into sql. It's definitely a bug in Slick 3.1 since relatively straight forward and simple queries are throwing run time exceptions.

It seems to be related to the number of joins done through `flatMap`s. A query with a couple inner joins works fine, but beyond that and we start getting errors. Recursion issue maybe?

**Comment by lisinge** [comment] 2015-10-16 12:45
Looks like this is the same problem i'm having in #1312. Building the query without using for comprehension works but results in this query with some `case`:

```sql
select 
x2.x3, x2.x4, x2.x5, x2.x6, x2.x7, x2.x8, x2.x9, x2.x10, x2.x11, x2.x12, x2.x13, x2.x14
from
(select x15."updated_at" as x5, x15."image" as x11, x15."valid_to" as x8, x15."geographical_scope_id" as x9,
x15."branding_id" as x6, x15."geographical_scope_type" as x4, x15."uri" as x13, x15."created_at" as x7, x15."id" as x10,
x15."valid_from" as x14, x15."weight" as x12, x15."title" as x3,
(case when (x16."id" is null) then null else 1 end) as x17, x16."image" as x18, x16."valid_to" as x19,
x16."link_url" as x20, x16."kuponginlosen_amount" as x21, x16."description" as x22, x16."coupon_kind_index" as x23,
x16."coupon_instructions" as x24, x16."active" as x25, x16."kind_index" as x26, x16."highlight" as x27, x16."tags" as x28, x16."created_at" as x29,
x16."popularity" as x30, x16."id" as x31, x16."terms" as x32, x16."kuponginlosen_campaign" as x33, x16."valid_hours" as x34, x16."static_coupon_code" as x35,
x16."valid_from" as x36, x16."link_text" as x37, x16."total_checkout_limit" as x38, x16."title" as x39, x16."individual_checkout_limit" as x40 from "featured_items" x15
left outer join "offers_new_structure" x16 on
(x15."geographical_scope_type" = 'Offer') and (x15."geographical_scope_id" = x16."id")) x2
left outer join "offers_spots" x41 on (case when (x2.x17 is not null) then x2.x31 else null end) = x41."offer_id"
left outer join "spots" x42 on x41."spot_id" = x42."id" where (x2.x4 is null) or (case when (x42."id" is not null) then ST_DWithin(x42."location",?,?,true) else null end)
```

Thanks @timgautier i didn't think about trying it without the for comprehension!

**Comment by lisinge** [comment] 2015-10-16 13:04
False alarm, i'm still getting `Unreachable reference to s2 after resolving monadic joins`

**Closed** 2015-10-27 17:21 UTC
Labels: 1 - Ready, bug, REGRESSION

**Comment by AmirKarimi** [comment] 2015-11-05 16:45
When this fix will be released?

**Comment by lisinge** [comment] 2015-11-16 10:43
I'm wondering the same thing, any ETA?

**Comment by enragedginger** [comment] 2015-11-20 06:19
I'm also having this issue. An ETA would be great.

**Comment by aloiscochard** [comment] 2015-11-20 14:04
+1 for having an ETA, this one prevent us from upgrading.

**Comment by lisinge** [comment] 2015-12-07 09:49
This one is really preventing us from upgrading. Can we get this update out or at least an ETA?

**Comment by aloiscochard** [comment] 2015-12-07 15:55
Same here, it's critical for upgrade and the workaround is so-so, I would prefer to avoid it until that get fixed.

**Comment by hepin1989** [comment] 2015-12-07 15:57
@aloiscochard publishLocal?

**Comment by szeiger** [comment] 2015-12-07 21:58
There are some more regressions I'd like to look into for a 3.1.1 but if I don't find the time before my Xmas vacation, we should probably cut a 3.1.1 just with this.

**Comment by lisinge** [comment] 2015-12-08 08:05
@szeiger Thanks for the quick response.
Yeah that's totally understandable, it's just that this is quite the show-stopper for some people it would be great with a 3.1.1 release with just this fix.
But this sounds great!

**Comment by aloiscochard** [comment] 2015-12-08 09:04
@szeiger thanks for the feedback Stefan!

That's perfect for me, I was planning a few upgrade for xmas holidays :-)

Cheers

**Comment by sweepy84** [comment] 2016-09-10 07:16
What's the status of this? Just upgraded a very large application and surprised something so fundamental isn't working.
Why is the bug closed?

**Comment by lisinge** [comment] 2016-09-10 07:34
@sweepy84 Might be because that the bug here was resolved but there still are more bugs, for example i opened a new issue here https://github.com/slick/slick/issues/1408

**Comment by sweepy84** [comment] 2016-09-10 07:36
thanks @lisinge!
