### ISSUE TITLE
Slick 3.2 Release Planning

### ISSUE THREAD

**Issue by szeiger** [slick/slick#1537] opened 2016-06-29 13:50 UTC
Let's plan a new Slick release. What we have so far:
- Slick Extensions drivers
- Important bug fixes (notably https://github.com/slick/slick/issues/1274)
- Usability and documentation improvements
- Probably some other interesting stuff that I haven't had a chance to examine yet (still making my way through the PRs and issues).

I'd like to release a 3.2.0-M1 on Friday so that we can finally get the bug fixes and new drivers out to customers.

What else should go into a 3.2.0 release? I'd like to work on https://github.com/slick/slick/issues/1532 and https://github.com/slick/slick/issues/1277 to address customer needs but I don't have any other major work planned.

/cc @radsaggi @pbatko @smootoo @d6y @tminglei

**Comment by cvogt** [comment] 2016-06-29 16:07
Ideally we'd try to get as many fixes from @radsaggi and @trevorsibanda in as we can, but I would not tie the release schedule to that. If they don't make it in for M1, we'll do M2.

**Comment by deusaquilus** [comment] 2016-06-29 17:47
I don't mean to pester but any chance a fix for #1408 could be included?

**Comment by cvogt** [comment] 2016-06-29 20:13
@deusaquilus let's look at it this way: we should get the M1 out asap. #1408 is unlikely to be fixed this week. Instead of delaying M1 until when it is, we should get M1 out now and when #1408 is out we'll release M2. We'll try to be better at getting releases out quickly. If somebody wants to join our crew of volunteers to speed things up in these regards, we are very open to that!

**Comment by cvogt** [comment] 2016-06-29 23:41
looks like this may be good to include https://github.com/slick/slick/pull/1539

**Comment by szeiger** [comment] 2016-07-01 14:58
Delaying M1 until next week. I hope we'll get a ScalaTest release for Scala 2.12.0-M5 over the weekend. Build and tests are working on M5 and I can run the reactive-streams-tests with ScalaTest 3.0.0-RC3 (the version that is supposed to be released for 2.12.0-M5), so I don't expect any surprises there, but I still want to play it safe to ensure we can release the same M1 build for 2.11 and 2.12.0-M5.

**Comment by szeiger** [comment] 2016-07-04 10:40
New ScalaTest is out. We should be able to build on 2.11 and 2.12.0-M5 now: https://github.com/slick/slick/pull/1549

**Comment by qdsang** [comment] 2016-07-18 14:26
#1277  fix ?

**Comment by sorenbs** [comment] 2016-08-28 14:41
What is the best way for me to keep up with the release process?

**Comment by cvogt** [comment] 2016-08-28 16:17
@sorenbs we announce things like this on the mailing list. If you only want releases you probably need an email filter.

**Comment by lisinge** [comment] 2016-08-31 12:24
Will we see a fix for #1408 in 3.2? And #1340 too perhaps?

**Comment by cvogt** [comment] 2016-08-31 13:38
@szeiger any time to look at especially the regression #1408 ?

**Comment by Elufimov** [comment] 2016-09-30 10:30
Any news?

**Comment by fractal** [comment] 2016-11-23 18:52
Any updates on the release plan. No news since 3.2.0-M1

**Comment by margussipria** [comment] 2016-11-24 13:00
Feels like mostly dead project, hopped that Scala 2.12.0 release would free some maintainers for this, but no. Some other projects would have at least publish 3.1.2 with critical bug fixes.

**Comment by sarahgerweck** [comment] 2017-01-22 17:10
@szeiger you mentioned in #1572 that you consider 3.2.0-M2 more suitable for production use than 3.0 or 3.1 because of #1274. If 3.2.0-M2 is really more solid than 3.1, I would like to implore you to release 3.2.0 (or a release candidate) as soon as possible (if not immediately). 

People are clearly a bit concerned about the ongoing lack of a Scala 2.12–compatible release, and #1274 is indeed a pretty concerning issue.

If there are more features that were planned for 3.2 that could be retargeted to 3.3 instead, I think that would be a good thing to do. Perhaps 3.2.0-M2 is good code, but a milestone build is generally not going to have a big enough install base for people to feel good about running it in production.

**Comment by gaydenko** [comment] 2017-01-22 17:25
I'm the next sharing Sarah's view in common and especially at #1274

**Comment by deusaquilus** [comment] 2017-01-23 00:41
Starting to agree with @margussipria, this project seems to be dying. The deadlock issue #1274 committed seven months ago isn't in production yet and people are still trying to figure out where to cut the branch. Regression issues have been sitting around for over a year despite a half-dozen people commenting that it's a showstopper for them (notably #1408) and offering to help testing (see #1674). If @szeiger cannot continue being a regular maintainer as seems to be the case, other people have to step up their game and make sure this project stays up to date. Otherwise Scala will need a new DB interaction library.

**Comment by szeiger** [comment] 2017-02-10 11:33
PR queue closed for RC1. Once the build passes, I'll cut a release.

**Comment by nafg** [comment] 2017-07-02 05:45
What's the status?

**Comment by nafg** [comment] 2017-07-02 05:47
Is there a reason this is still open?

**Comment by cvogt** [comment] 2017-07-03 19:23
I guess no

**Closed by cvogt** 2017-07-03 19:23 UTC
