### ISSUE TITLE
Joins become nested selects, slow on MySQL

### ISSUE THREAD

**Issue by fernandezpablo85** [slick/slick#623] opened 2014-01-23 15:41 UTC
Here's the full thread:

https://groups.google.com/forum/#!topic/scalaquery/EXihfXbHmSI

This is making some queries go from 11 seconds to 5 minutes (see "ijuma" comment on that thread).

**Comment by szeiger** [comment] 2015-01-29 15:25
Rescheduling to 3.1. Rewriting the last few phases of the query compiler to fix these issues should become one of the big topics for 3.1.

**Comment by papauschek** [comment] 2015-01-29 21:50
Glad to hear that this issue is being picked up :)

**Comment by pathikrit** [comment] 2015-02-08 07:08
+1

It also causes some surprising behaviours when mixed in with ORDER BY DESC and LIMIT. The LIMIT goes to the inner join clause but the ORDER BY DESC is on the outer select which is incorrect because you want the ORDER BY DESC to go to the inner join for limit to work correctly.

**Comment by pathikrit** [comment] 2015-02-08 07:15
I would add the incorrect tag to this bug.

These should be equivalent:
```scala
Users.join(Addresses).leftJoinOn(_.addressId === _.id).drop(10).take(50).orderBy(_._1.id.desc)
Users.orderBy(_.id.desc).join(Addresses).leftJoinOn(_.addressId === _.id).drop(10).take(50)
```

But they are not. The second one is doing what is expected from the first one.

**Comment by pathikrit** [comment] 2015-02-08 07:18
I would add the incorrect tag to this bug.

These should be equivalent:
```scala
// Get the last 50 users (paginated by 10) who logged in along with their addresses
val q1 = Users.leftJoin(Addresses).on(_.addressId === _.id).drop(10).take(50).orderBy(_._1.loginTime.desc)

val q2 = Users.orderBy(_.logTime.desc).leftJoin(Addresses).on(_.addressId === _.id).drop(10).take(50)
```

But they are not. The second one is doing what is expected from the first one.

**Comment by pathikrit** [comment] 2015-02-08 07:21
I would like to add the incorrect tag to this bug.

These should be equivalent:
```scala
// Get the last 50 users (paginated by 10) who logged in along with their addresses

val q1 = Users.leftJoin(Addresses).on(_.addressId === _.id).drop(10).take(50).orderBy(_._1.loginTime.desc)

val q2 = Users.sortBy(_.logTime.desc).leftJoin(Addresses).on(_.addressId === _.id).drop(10).take(50)
```

But they are not. The second one is doing what is expected from the first one.

The first one is putting the order by on the outer select statement but the limit on the inner join statement which is producing incorrect results. It is fixed by using the second way where we order by upfront before the join to get around this issue of redundant outer selects

**Comment by kjim** [comment] 2015-04-20 02:54
+1

**Comment by nicky-isaacs** [comment] 2015-05-28 20:17
+1

**Comment by trobison** [comment] 2015-05-28 20:21
Just reading this makes me fear adopting slick.  MySQL has its flaws and I would love to have some beers and rant about them, but every other way I can talk to MySQL doesn't come bundled with this limitation.

+1

**Comment by szeiger** [comment] 2015-05-28 20:26
@pathikrit This is the expected behavior. You take the first 50 elements from an unordered view, and then sort those elements. That's different from first sorting and then taking the first 50 from the sorted view. It's the same for Scala collections.

**Comment by cvogt** [comment] 2015-05-28 22:58
@szeiger is this in the scope of your 3.1 compiler enhancement?

**Comment by szeiger** [comment] 2015-05-29 08:54
@cvogt What exactly, eliminating the nesting? Sure, that's the whole whole point of it. Pretty much as requested in https://github.com/slick/slick/issues/623#issuecomment-64932417. Or the correct propagation of ORDER BY clauses through subqueries? Possibly, time permitting. Currently there are still some situations where it doesn't happen. Eliminating most of the subqueries should further marginalize these cases, but we could eliminate them entirely with some more work.

**Comment by szeiger** [comment] 2015-06-24 09:40
Duplicate of #489

**Closed by szeiger** 2015-06-24 09:40 UTC
Labels: improvement, UPVOTED
