### ISSUE TITLE
If using postgres, generate string as TEXT, not VARCHAR(254)

### ISSUE THREAD

**Issue by strelec** [slick/slick#956] opened 2014-08-06 09:40 UTC
I have noticed that when you have string in you slick object, you get VARCHAR(254) in generated schema. So, at least for postgres (if not for other engines too), it's better to just use TEXT.

http://www.postgresql.org/docs/9.4/interactive/datatype-character.html

> Tip: There are no performance differences between these three types, ...

**Comment by arivero** [comment] 2015-01-18 16:50
@strelec my only guess is that 254 is the limit for Pascal strings (limit is 255) that are C-compatible (need a zero byte at the end).

**Comment by szeiger** [comment] 2015-01-29 10:39
Duplicate of #129

**Closed by szeiger** 2015-01-29 10:39 UTC
Labels: 1 - Ready, improvement
