### ISSUE TITLE
Slick insertOrUpdate failing on on table with two columns combined to be primary key

### ISSUE THREAD

**Issue by Christewart** [slick/slick#1644] opened 2016-11-08 20:39 UTC
I'm trying to use `insertOrUpdate` on a table with two primary keys. Here is how the primary key is defined: 

```scala
  def playerId = column[Long]("player_id")
  def gameId = column[Long]("game_id")
  //creates a pk using two columns in the database
  //see: https://stackoverflow.com/questions/33704436/creating-a-composition-primary-key-using-scala-slick/33704773#33704773
  def pk = primaryKey("box_score_pk", (playerId, gameId))
```

When I try and invoke `table.insertOrUpdate(...)` on this table, I get SQL generated with empty `where` clauses when trying to find a record in the database. Has anyone seen this issue, or know a fix for it? This is using `slick.driver.PostgresDriver.api._`

EDIT: 
Here is the stack trace: http://pastebin.com/nBiLwvg2

**Comment by cvogt** [comment] 2016-11-08 20:45
looks like a duplicate of https://github.com/slick/slick/issues/1627 . Please reopen if it is not.

**Closed by cvogt** 2016-11-08 20:45 UTC
