### ISSUE TITLE
ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by hwandonggit** [slick/slick#1469] opened 2016-03-23 21:41 UTC
Hi, 

I am trying to use slick with Oracle. I can not find much discussion regarding Oracle support. I have the following compile error from "sbt compile", can someone comment?:

===============================
[error] C:\SourceCode\test\DatabaseConfigOracle.scala:9: object OracleProfile is not a member of package slick.driver
[error]   val driver = slick.driver.OracleProfile
[error]                             ^
[error] [error] C:\SourceCode\test\DatabaseConfigOracle.scala:12: not found: type Session
[error]   implicit val session: Session = db.createSession()
[error]                         ^
[error] C:\SourceCode\test\DatabaseConfigOracle.scala:14: not found: value Database
[error]   def db = Database.forConfig("oracledb")
[error]            ^
[error] three errors found
[error] (compile:compile) Compilation failed
[error] Total time: 2 s, completed Mar 23, 2016 2:38:05 PM
===============================

Code is as following:
--------------------------------------------------------
import com.typesafe.slick.driver.oracle.OracleDriver

trait DatabaseConfigOracle extends OracleDriver{
  val driver = slick.driver.OracleProfile

  import driver.api._
  implicit val session: Session = db.createSession()

  def db = Database.forConfig("oracledb")

------------------------------------------

build.sbt:
...

libraryDependencies ++= Seq(
  "com.typesafe.akka" % "akka-http-spray-json-experimental_2.11" % "2.0.3",
  "com.typesafe.slick" %% "slick" % "3.1.1",
  "com.typesafe.slick" %% "slick-extensions" % "3.0.0",
  "mysql" % "mysql-connector-java" % "5.1.37",
  "org.scalatest" % "scalatest_2.11" % "2.2.4" % "test"
)

Revolver.settings

resolvers += "Typesafe Releases" at "http://repo.typesafe.com/typesafe/maven-releases/"

**Comment by hwandonggit** [comment] 2016-03-23 22:36
After changing the code to the following, 

//import com.typesafe.slick.driver.oracle.OracleDriver

trait DatabaseConfigOracle {
  val driver = com.typesafe.slick.driver.oracle.OracleDriver

  import driver.api._
  implicit val session: Session = db.createSession()

  def db = Database.forConfig("oracledb")

Hit the following error:
[error] missing or invalid dependency detected while loading class file 'OracleDriver.class'.
[error] Could not access term computeQueryCompiler in trait slick.driver.JdbcProfile,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problem
[error] A full rebuild may help if 'OracleDriver.class' was compiled against an incompatible v
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 3 s, completed Mar 23, 2016 3:36:45 PM

**Comment by smootoo** [comment] 2016-03-23 22:55
slick and slick-extensions need to be the same version (they are at 3.1.1 and 3.0.0 in your example). Since slick-extensions depends on slick, I would suggest changing the dependencies to 
```
libraryDependencies ++= Seq(
"com.typesafe.akka" % "akka-http-spray-json-experimental_2.11" % "2.0.3",
"com.typesafe.slick" %% "slick-extensions" % "3.1.0",
"mysql" % "mysql-connector-java" % "5.1.37",
"org.scalatest" % "scalatest_2.11" % "2.2.4" % "test"
)
```

**Comment by cvogt** [comment] 2016-03-24 00:03
@hwandonggit looks like not a bug. please re-open if that is incorrect.

**Comment by hwandonggit** [comment] 2016-03-24 00:10
Hi smootoo and cvogt, 

Thank you. Your suggestion does solve my compilation issue. But I hit another issue when I test it. I am sure Oracle configuration on my local machine is correct(checked couple of things, including tnsping etc. ). Any more comments are really appreciated!

[ERROR] [03/23/2016 17:04:29.034] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:673)
        at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:715)
        at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:564)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:98)
        at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:61)
        at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
        at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
        at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297)
        at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
        at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
        at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
        at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
        at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218)
        at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

My oracle config in application.conf is as following:
oracledb = {
  url = "jdbc:oracle:thin://localhost:1521/xe"
  driver = oracle.jdbc.OracleDriver
  user = "dbuser"
  password = "testtest"
  connectionPool = disabled
  keepAliveConnection = true
  enabled = true
}

**Comment by szeiger** [comment] 2016-03-24 17:21
Did you mean `jdbc:oracle:thin:@//localhost:1521/xe`? AFAIK the `@` is required.

**Comment by hwandonggit** [comment] 2016-03-24 21:45
Hey szeiger, 

Thank you! Your suggestion of adding "@" does solve my problem. Even though I hit other problem now, I would think this issue can be closed. 

Thank you all!

**Comment by hwandonggit** [comment] 2016-03-25 02:58
Hello Stefan, 

Thanks for your suggestions earlier. But I hit another issue, after some research, trying, debugging, I am sure if it is not a simple mistake from my side, but of course I can not tell it is a bug from slick extension for Oracle.  I hit the following issue: "ORA-00942: table or view does not exist", I am sure the table is there and privilege is correct. Could you advise?

Here is backtrack:

java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
        at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
        at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:507)
        at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:504)
        at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:347)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
        at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
        at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504)
        at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
        at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

After I enabled debug info, here are more details: 
19:57:10.935 [default-akka.actor.default-dispatcher-8] DEBUG slick.compiler.CodeGen - Compiled server-side to:
| CompiledStatement "insert into "txs_sm" ("id","extid","request","state","substate","response","starttime","endtime")  values (?,?,?,?,?,?,?,?)" : (String', String', String', String', String', String', String', String')

19:57:10.942 [default-akka.actor.default-dispatcher-8] DEBUG slick.compiler.QueryCompiler - After phase codeGen:
| ResultSetMapping : Vector[(String', String', String', String', String', String', String', String')]
|   from s5: CompiledStatement "insert into "txs_sm" ("id","extid","request","state","substate","response","starttime","endtime")  values (?,?,?,?,?,?,?,?)" : (String', String', String', String', String', String', String', String'
|   map: CompiledMapping : Mapped[(String', String', String', String', String', String', String', String')]
|     converter: TypeMappingResultConverter
|       child: ProductResultConverter
|         1: SpecializedJdbcResultConverter$$anon$1 idx=1, name=id : String'
|         2: SpecializedJdbcResultConverter$$anon$1 idx=2, name=extid : String'
|         3: SpecializedJdbcResultConverter$$anon$1 idx=3, name=request : String'
|         4: SpecializedJdbcResultConverter$$anon$1 idx=4, name=state : String'
|         5: SpecializedJdbcResultConverter$$anon$1 idx=5, name=substate : String'
|         6: SpecializedJdbcResultConverter$$anon$1 idx=6, name=response : String'
|         7: SpecializedJdbcResultConverter$$anon$1 idx=7, name=starttime : String'
|         8: SpecializedJdbcResultConverter$$anon$1 idx=8, name=endtime : String'

19:57:10.957 [default-akka.actor.default-dispatcher-8] DEBUG s.compiler.QueryCompilerBenchmark - ------------------- Phase: Time ---------
19:57:10.959 [default-akka.actor.default-dispatcher-8] DEBUG s.compiler.QueryCompilerBenchmark -       assignUniqueSymbols:   14.801335 ms
19:57:10.959 [default-akka.actor.default-dispatcher-8] DEBUG s.compiler.QueryCompilerBenchmark -                inferTypes:    5.943963 ms
19:57:10.959 [default-akka.actor.default-dispatcher-8] DEBUG s.compiler.QueryCompilerBenchmark -            insertCompiler:   14.010693 ms
19:57:10.961 [default-akka.actor.default-dispatcher-8] DEBUG s.compiler.QueryCompilerBenchmark -                   codeGen:   53.311278 ms
19:57:10.961 [default-akka.actor.default-dispatcher-8] DEBUG s.compiler.QueryCompilerBenchmark -                     TOTAL:   88.067269 ms
19:57:10.965 [default-akka.actor.default-dispatcher-8] DEBUG s.backend.DatabaseComponent.action - #1: SingleInsertAction [insert into "txs_sm" ("id","extid","request","state","substate","response","starttime","endtime")  values (?
,?,?)]
19:57:10.975 [oracledb-1] DEBUG slick.jdbc.JdbcBackend.statement - Preparing statement: insert into "txs_sm" ("id","extid","request","state","substate","response","starttime","endtime")  values (?,?,?,?,?,?,?,?)
[ERROR] [03/24/2016 19:57:11.294] [default-akka.actor.default-dispatcher-6] [akka://default/user/$a] ORA-00942: table or view does not exist

java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)

**Comment by hwandonggit** [comment] 2016-03-25 02:59
Hi Stefan, 

We saw some discussion here, is it related?
 https://groups.google.com/forum/#!topic/scalaquery/U431n-Z2cwM

Thank you,

**Comment by hwandonggit** [comment] 2016-03-27 22:32
Hi, 

I still have such an issue:  ORA-00942: table or view does not exist. If there are no comments, can someone share some example of slick/oracle so that I can compare what could be wrong? thanks

**Comment by hwandonggit** [comment] 2016-03-30 00:57
Hi Jan Christopher Vogt, 

Can you refer to some sample code? I am currently evaluating slick solution for Oracle. 

thank you,

**Comment by hwandonggit** [comment] 2016-03-30 18:08
Issue has been identified and solved. table name and column names have to be upper cases. Thanks!

**Comment by cvogt** [comment] 2016-03-30 23:54
@hwandonggit glad to hear!

**Comment by cvogt** [comment] 2016-03-30 23:55
seems like we are all set here. closing. reopen if necessary.

**Closed by cvogt** 2016-03-30 23:55 UTC
