### ISSUE TITLE
Incorrect SQL in Slick 3.1.0-M2 for `optColumn =!= None`

### ISSUE THREAD

**Issue by TimothyKlim** [slick/slick#1258] opened 2015-08-26 16:08 UTC
Hi!

I have validator for checking a phone number to unique:
```scala
val id: Option[Long] = None
...
table.filter { q =>
  (q.id =!= id) && (q.phoneNumber === phoneNumber)
}.take(1).exists.result
```
and slick generates this **incorrect** query:
```sql
select exists(
  select ...
  from ...
  where
    (not ("id" = null))
      and ("mobile_phone_number" = 71111111111)
  limit 1
) -- always return false
```
instead of this:
```sql
select exists(
  select ...
  from ...
  where
    ("id" IS NOT NULL)
      and ("mobile_phone_number" = 71111111111)
  limit 1
)
```
*tested on PostgreSQL 9.4.4*

**Comment by szeiger** [comment] 2015-08-26 16:47
This is the expected behavior. Duplicate of #947.

**Closed by szeiger** 2015-08-26 16:47 UTC
