### ISSUE TITLE
SQLServerDriver: Invalid SQL when upserting to table with one column

### ISSUE THREAD

**Issue by JohnAtWork** [slick/slick#1637] opened 2016-11-02 21:48 UTC
I'm using slick 3.1.1 with slick-extensions 3.1.0.  I'm connecting to a MS SQL 2014 database using the net.sourceforge.jtds driver.  

I have a table defined like this:

    class MyTable(tag: Tag) extends Table[(Int)](tag, "MyTable") {
        def id = column[Int]("ID", O.PrimaryKey)
        def * = (id)
      }
      val myTables = TableQuery[MyTable]

When I run myTables.insertOrUpdate(newId) logs report:

    [debug] s.j.J.statement - Preparing statement: merge into "MyTable" t using (select ? as "ID") s on (t."ID"=s."ID") when matched then update set  when not matched then insert ("ID") values (s."ID");
This is an invalid merge statement (update portion doesn't set any fields).  When slick tries to execute the statement, a java.sql.SQLException is thrown.  

The problem does not occur when using the H2 driver.

**Comment by hvesalai** [comment] 2018-02-28 17:30
Duplicate of #1728

**Closed by hvesalai** 2018-02-28 17:30 UTC
