### ISSUE TITLE
Hello Slick template page does not exists.

### ISSUE THREAD

**Issue by salehkhazaei** [slick/slick#1954] opened 2018-09-30 09:53 UTC
The Hello Slick template link in http://slick.lightbend.com/doc/3.2.3/introduction.html does not exists.
It refers to https://www.lightbend.com/activator/template/hello-slick-3.2

**Comment by d6y** [comment] 2018-10-01 08:36
Thanks for the report. This looks like a duplicate of https://github.com/slick/slick/issues/1789

**Closed by d6y** 2018-10-01 08:36 UTC
