### ISSUE TITLE
Unable to use String extension methods with mappedColumnType

### ISSUE THREAD

**Issue by legramira** [slick/slick#1414] opened 2016-01-07 03:40 UTC
Assuming you have a

``` scala
case class Email(email: String) extends AnyVal
```

and a mapped column type like

``` scala
  implicit val emailTypeMapper = MappedColumnType.base[Email, String](
    email => email.email,
    s => Email(s)
  )
```

If you try to write a query like

``` scala
val q = Users.filter(user => user.email.toLowerCase === someEmail) //someEmail is of type Email
```

you get a compile error that `.toLowerCase` is not a method of `Rep[Email]`, however `.toLowerCase` is a method for `Rep[String]` which is what the mapping goes to.

**Comment by kpmeen** [comment] 2017-02-21 18:34
You will need to make an implicit available in scope that adds the `toLowerCase` method to columns of type `Email`.

This works nicely for me, for the exact same use-case as you're describing:

```scala
  implicit class EmailColumnExtensionMethods[P1](val c: Rep[Email]) {
    implicit def emailTypedType = implicitly[TypedType[Email]]

    def toLowerCase(implicit tt: TypedType[Email]) = Library.LCase.column[Email](c.toNode)
  }
```
You will then be able to perform the query you want to write using the `toLowerCase` method on the `Email` type.

**Comment by cvogt** [comment] 2017-02-22 00:25
duplicate of https://github.com/slick/slick/issues/967

**Closed by cvogt** 2017-02-22 00:25 UTC

**Comment by quelgar** [comment] 2017-07-20 05:52
I found a simpler way to do this, which gives you all the string extension methods in one hit:

```scala
implicit def emailColumnExtensionMethods(c: Rep[Email]): slick.lifted.StringColumnExtensionMethods[Email] =
  new slick.lifted.StringColumnExtensionMethods[Email](c)
```

Seems to be working ok for me.

It seems like the library implicit should work for anything that had a mapping to `String`. I couldn't figure out how to do it, though.

Weirdly, this compiles, and works for all types:

```scala
implicit def anyStringExtensionMethods[A](c: Rep[A]): slick.lifted.StringColumnExtensionMethods[A] =
  new slick.lifted.StringColumnExtensionMethods[A](c)
```

but it's not type-safe ☹️

**Comment by Dasiu** [comment] 2017-07-27 19:30
Scala 2.12, Slick 3.2

kpmeen's solution does not compile for me, there is not such a method like `column` in `Library.LCase.column`. I do not know how transform that snippet or if its still possible in Slick 3.2.

quelgar's solution returns for me following compilation error:

>  Cannot perform option-mapped operation
 with type: (commons.models.Login, String) => R
   for base type: (String, String) => Boolean
 Error occurred in an application involving default arguments.
             (userTable.login like "%test%")

```
case class Login(value: String) extends AnyVal
```
```
protected class UserTable(tag: Tag) extends IdTable[ModelId, Model](tag, "user") {
    def login: Rep[Login] = column[Login]("login")

    def * : ProvenShape[Model] = (id, login) <> (User.tupled, User.unapply)
  }
```
```
implicit val loginMapping: BaseColumnType[Login] = MappedColumnType.base[Login, String](
    login => login.value,
    str => Login(str)
  )
```

**Comment by im-tollu** [comment] 2017-08-21 14:27
For `.column` to be available use 
```import slick.lifted.FunctionSymbolExtensionMethods.functionSymbolExtensionMethods```
