### ISSUE TITLE
java.lang.StackOverflowError when using reduceLeft on filter

### ISSUE THREAD

**Issue by phwiget** [slick/slick#1844] opened 2018-02-05 11:52 UTC
Slick 3.2/3.1

Reported on mysql as well as postgres profiles.

If one uses `reduceLeft` in the `filter` clause, there may be a `java.lang.StackOverflowError`, if the Array reduced is too big.
We could not really figure, how big the Array maybe, it seems, that this also depends on the machine running the code.
Example, where `usernames` is a `Seq[String]` (note that error also occurs when using `result` instead of `delete`)
```
val query = for{
        d <- users.filter(u => usernames.map(username => u.username === username).reduceLeft(_ || _)).delete
} yield d
```
As a workaround one may use `DBIO.sequence(...)` in a transaction.

**Comment by phwiget** [comment] 2018-02-05 11:55
Some stacktrace: 
```
Feb 05 03:56:33 [74900]: java.lang.StackOverflowError
Feb 05 03:56:33 [74900]: at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:55)
Feb 05 03:56:33 [74900]: at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)
Feb 05 03:56:33 [74900]: at slick.util.ConstArray.endoMap(ConstArray.scala:122)
Feb 05 03:56:33 [74900]: at slick.ast.Node.mapChildren(Node.scala:50)
Feb 05 03:56:33 [74900]: at slick.ast.Node.mapChildren$(Node.scala:48)
Feb 05 03:56:33 [74900]: at slick.ast.Apply.mapChildren(Node.scala:546)
Feb 05 03:56:33 [74900]: at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
Feb 05 03:56:33 [74900]: at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.
...
```

**Comment by djx314** [comment] 2018-02-05 13:40
You can use `inSet` or `inSetBind`
```scala
db.run(users.filter(u => u.username inSet usernames).delete)
```

**Comment by WellingR** [comment] 2018-02-19 08:42
In this case inSetBind is an option however it would not be possible in a case similar to the following:

```scala
val query = for{
        d <- users.filter(u => usernames.map(firstAndLastName => u.firstName === firstAndLastName.firstName && u.lastName === firstAndLastName.lastName).reduceLeft(_ || _)).delete
} yield d
```

I have encountered this issue before, and worked around it by using several queries for things like this.  But I would really appreciate if this was fixed.

**Comment by takezoe** [comment] 2018-02-19 10:37
This looks similar to https://github.com/slick/slick/issues/1606.

**Comment by hvesalai** [comment] 2018-03-01 19:20
Duplicate of #1606

**Closed by hvesalai** 2018-03-01 19:20 UTC

**Comment by hongBry** [comment] 2018-04-20 16:06
I also have this issue，does it fixed？
