### ISSUE TITLE
Allow passing columns for filtering with inSet & inSetBind

### ISSUE THREAD

**Issue by sjbog** [slick/slick#1351] opened 2015-11-08 02:12 UTC
In v3.1.0 method `inSet` requires argument sequence `Seq[T]` to contain types of the column `Rep[T]`
Issue: allow passing seq containing actual columns with same type `Seq[Rep[T]]`
As an extra allow some other related types and/or any column types.

Example:
```
val transformFn = SimpleFunction[Date]("DATE")
val data: Seq[Rep[Date]] = input.map(transformFn(_))

db.run(
    query.withFilter( t => t.date inSet data).result
)
```

**Comment by cvogt** [comment] 2016-07-25 15:48
this may be somewhat related to @radsaggi's work on mutating updates. Maybe he has time to look at this at some point

**Comment by cvogt** [comment] 2016-07-25 15:49
also vaguely related to https://github.com/slick/slick/issues/517

**Comment by cvogt** [comment] 2016-07-25 15:50
duplicate of https://github.com/slick/slick/issues/718

**Closed by cvogt** 2016-07-25 15:50 UTC
