### ISSUE TITLE
Slick ddl create tables order with foreign key dependency on other tables don't work

### ISSUE THREAD

**Issue by vikasdp** [slick/slick#993] opened 2014-09-23 22:04 UTC
running ddl slick throws sql exceptions due to it trying to create tables which have foreign key on other tables which aren't yet created. details are at http://stackoverflow.com/questions/25983759/slick-ddl-create-table-order-with-foreign-key-dependency-on-other-tables

**Comment by szeiger** [comment] 2015-01-29 15:18
Closing since we have no way to reproduce this issue.

**Closed by szeiger** 2015-01-29 15:18 UTC
Labels: bug
