### ISSUE TITLE
 distinctOn doesn't seem to work

### ISSUE THREAD

**Issue by cvogt** [slick/slick#1712] opened 2017-03-27 22:45 UTC

**Comment by cvogt** [comment] 2017-03-27 22:46
@nafg writes:
> his doesn't have tests for distinctOn. It doesn't seem to work -- it puts all the columns in the ON list, not just the one I specified.

see https://github.com/slick/slick/pull/1271#issuecomment-289607725

**Comment by nafg** [comment] 2017-03-28 23:14
Thanks for opening. ;) Possible duplicate of #1340

**Comment by klclee** [comment] 2018-02-03 11:42
Hi guys is there some advance in this? Coming on the same problem

**Comment by hvesalai** [comment] 2018-02-28 16:56
Duplicat eof #1340

**Closed by hvesalai** 2018-02-28 16:56 UTC
Labels: bug
