### ISSUE TITLE
When using optional Oracle RAW type query parameters: [SQLException: ORA-00932: inconsistent datatypes: expected - got BLOB ]

### ISSUE THREAD

**Issue by refried** [slick/slick#195] opened 2013-08-17 06:37 UTC
Not sure how to move forward with this...
The tables are using the Oracle RAW type for PK, not BLOB.  They are both mapped to Array[Byte], not sure if that's relevant.

```scala
trait TypedId extends Any {
  def untypedId: Array[Byte]
  override def toString = untypedId.map("%02X" format _).mkString
}

type WrappedIdType = Array[Byte]
case class CityId(untypedId: WrappedIdType) extends AnyVal with TypedId

def doSearch(cityId: Option[CityId]) = {
    val query = for {
      cityIdFilter <- Parameters[Option[CityId]]
      agency <- Agency if (cityIdFilter.isNull || cityIdFilter.get === agency.cityId)
    } yield agency.name

    Logger.info(query.selectStatement) 
    // select x2."NAME" from "TB_AGENCY" x2 where (? is null) or (? = x2."CITY_ID")

    db withSession query.list(cityId) // Execution exception
}
```

Runs fine if the parameter type is not an Option, e.g.:
```scala
    val query = for {
      cityIdFilter <- Parameters[CityId]
      agency <- Agency if (cityIdFilter.isNull || cityIdFilter === agency.cityId)
    } yield agency.name
    Logger.info(query.selectStatement)
    // select x2."NAME" from "TB_AGENCY" x2 where (? is null) or (? = x2."CITY_ID")
    db run query.list((for (c <- City) yield c.id).first())
```

Thanks!

**Comment by szeiger** [comment] 2015-02-19 13:05
It is caused by comparing BLOB values with `=` (see http://stackoverflow.com/questions/12589937/ora-00932-inconsistent-datatypes-expected-got-blob). Fixed in 3.0.0.

**Closed** 2015-02-20 16:24 UTC
Labels: 3 - Done, bug, topic:slick-extensions
