### ISSUE TITLE
Reduce number of methods calls in single-expression in generated code

### ISSUE THREAD

**Issue by cvogt** [slick/slick#978] opened 2014-09-04 00:27 UTC
Instead of
```
A.ddl + B.ddl + ... + Z.ddl
```
we should emit
```
List(A.ddl, B.ddl, …, Z.ddl).reduceLeft(_ ++ _)
```

**Comment by szeiger** [comment] 2015-01-26 12:31
Duplicate of #854

**Closed by szeiger** 2015-01-26 12:31 UTC
Labels: bug, topic:type-providers
