### ISSUE TITLE
a StackOverflow Error caused by endless loop.

### ISSUE THREAD

**Issue by LoranceChen** [slick/slick#1752] opened 2017-06-26 13:08 UTC
```
java.lang.StackOverflowError
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:172)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
```

Currently,I just has the trace stack info.Does someone has same error?

**Comment by LoranceChen** [comment] 2017-06-26 13:09
limit data count could solve the problem temporarily

**Comment by LoranceChen** [comment] 2017-06-28 03:18
It will caused by such query operation:
`db.run(chartScheme.filter(chart => creatorIds.map(chart.creatorId === _).foldLeft(false: Rep[Boolean])(_ || _)).result)`

NOT 100% occurred. All of mysql connection status become CLOSE_WAIT once appear.

**Comment by WellingR** [comment] 2017-11-11 12:24
I have had this issue occur too. Basically it happens when query conditions are created from collections of 200+ elements using a foldLeft or reduce statement as shown in the comment above

**Comment by hvesalai** [comment] 2018-02-28 16:43
Monads need to be trampolined.

**Comment by hvesalai** [comment] 2018-03-01 19:28
Duplicate of #1606

**Closed by hvesalai** 2018-03-01 19:28 UTC
