### ISSUE TITLE
Using greater than or less than with implicit mapping for java.util.Date

### ISSUE THREAD

**Issue by terhechte** [slick/slick#194] opened 2013-08-16 14:07 UTC
Hey,

I'm using Slick together with Swagger, which is a library that automatically generates API descriptions and client code out of the actual code implementation (in my case my Scalatra implementation).

Swagger does not support java.sql.Date, as soon as I use that type, Swagger crashes. So I changed my db and made all columns java.util.Date and added an implicit Mapper for Slick:

```Scala
  implicit val JavaUtilDateTypeMapper = 
  MappedTypeMapper.base[java.util.Date, java.sql.Date] (
  x => new java.sql.Date(x.getTime),
  x => new java.util.Date(x.getTime))
```

One of my tables looks like this:
```Scala
object BoothExceptions extends Table[BoothException]("booth_exceptions") {
  def id = column[Int] ("boe_id", O.PrimaryKey, O.AutoInc)
  def closedDate = column[java.util.Date] ("boe_date")
```

However, now, when I try to build a query that returns all objects above a certain level, like so:
```Scala
                val q = for {
                  rs <- BoothExceptions
                  if rs.closedDate > theLocalDate
                } yield rs
```

I get this error:
```bash
value > is not a member of scala.slick.lifted.Column[java.util.Date]
```

Can I somehow teach Slick to use <, >, <= and >= ?

**Comment by szeiger** [comment] 2015-01-29 11:49
Duplicate of #967

**Closed by szeiger** 2015-01-29 11:49 UTC
Labels: bug, GSOC: More ops
