### ISSUE TITLE
Inner Join Too Slow

### ISSUE THREAD

**Issue by gguan** [slick/slick#1178] opened 2015-06-24 08:57 UTC
I create a query in SLICK grammer like this 
```scala
val query = for {
          (mark, tag) <- marks join tags on (_.tagId === _.id)
          if mark.id inSet cachedMarks.keySet
        } yield (mark.id, tag.tagName)
```
And SLICK generate the SQL query
```
select x2.x3,
       x4.x5
  from(
select x6.`tag_id` as x7, x6.`id` as x3, x6.`likes` as x8, x6.`post_id` as x9, x6.`created` as x10, x6.`user_id` as x11, x6.`updated` as x12
  from `mark` x6) x2 inner join(
select x13.`tag` as x5, x13.`id` as x14, x13.`likes` as x15, x13.`created` as x16, x13.`user_id` as x17, x13.`updated` as x18
  from `tag` x13) x4 on x2.x7= x4.x14
 where x2.x3 in(30609, 30875, 30829, 30856, 30825, 30717, 30805, 30714, 30608);
```

While this query can be simply written like this
```
select x2.id, x4.tag from mark x2 inner join tag x4 on x2.`tag_id` = x4.id  where x2.`id` in (30609, 30875, 30829, 30856, 30825, 30717, 30805, 30714, 30608);
```

And slick is about 4 times slower than the simple SQL. Any suggestions how to prevent SLICK from generating over complicate SQL?

**Comment by szeiger** [comment] 2015-06-24 09:49
Duplicate of #489. Try #1133 is you need a fix immediately.

**Closed by szeiger** 2015-06-24 09:49 UTC
