### ISSUE TITLE
Slick Upserting

### ISSUE THREAD

**Issue by YvanZhong** [slick/slick#1527] opened 2016-06-17 06:04 UTC
version:3.1.1
database:PostgreSQL 

description:
CREATE TABLE user_info (
    phone VARCHAR(63) NOT NULL,
    club    VARCHAR(255) NOT NULL,
    name  VARCHAR(255) NOT NULL,
    PRIMARY KEY (phone, club)
);
Then I generated Table with  code generator and used 'insertOrUpdate'. Exception as follows
org.postgresql.util.PSQLException: ERROR: syntax error at end of input

**Comment by tminglei** [comment] 2016-06-17 08:18
Hi @YvanZhong can you describe more details about your usage? And the detailed error message?

**Comment by Diagoras** [comment] 2016-06-23 16:02
I think this is a duplicate of https://github.com/slick/slick/issues/966

**Closed** 2017-07-21 12:27 UTC
